### ISSUE TITLE
Set Thumbnail doesn't work

### ISSUE THREAD

**Issue by ppasq** [HaitiData/haitidata#84]
Getting an error when trying to set a layer thumbnail: Can't find variable: createMapThumbnail

**Comment by gmtoglia** [comment]
FYI when creating a layer using the "Upload ODK exports" the thumbnail is set. I hope this can help.

![image](https://user-images.githubusercontent.com/16922193/32066981-93d56dae-ba4f-11e7-9bd0-c019a67db9d1.png)

**Comment by ppasq** [comment]
Fixed with #135

**Comment by gmtoglia** [comment]
The problem still persist when setting the thumbnail of a map:

![image](https://user-images.githubusercontent.com/16922193/33037560-f4f31fe6-cdff-11e7-8fa0-4eb0add3ae19.png)
